# Generated by Django 4.0.4 on 2022-04-15 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0002_candidate_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='voters',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
